#!/usr/bin/env python
# coding: utf-8

# In[1]:


# for NBC
import requests
from bs4 import BeautifulSoup


res = requests.get('https://www.nbcnews.com/politics/joe-biden/gop-sen-tim-scott-says-dems-are-pulling-us-further-n1265754')
soup = BeautifulSoup(res.text , 'html.parser')
articles = soup.select('.article-body__content p')
for p in articles:
    print(p.text)


# In[2]:


# for cnn
from newspaper import Article
article = Article('https://edition.cnn.com/2021/04/28/politics/rudy-giuliani-federal-prosecutors/index.html')
article.download()
article.parse()
print(article.text)





